package com.smartfactory.model.dao;

import com.smartfactory.model.entity.Bforminfo;
import com.smartfactory.model.entity.BforminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BforminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    long countByExample(BforminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByExample(BforminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByPrimaryKey(Integer bfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insert(Bforminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insertSelective(Bforminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    List<Bforminfo> selectByExample(BforminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    Bforminfo selectByPrimaryKey(Integer bfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bforminfo record, @Param("example") BforminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExample(@Param("record") Bforminfo record, @Param("example") BforminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKeySelective(Bforminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bforminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKey(Bforminfo record);
}