package com.smartfactory.model.dao;

import com.smartfactory.model.entity.Forminfo;
import com.smartfactory.model.entity.ForminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    long countByExample(ForminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByExample(ForminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByPrimaryKey(Integer formid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insert(Forminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insertSelective(Forminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    List<Forminfo> selectByExample(ForminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    Forminfo selectByPrimaryKey(Integer formid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Forminfo record, @Param("example") ForminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExample(@Param("record") Forminfo record, @Param("example") ForminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKeySelective(Forminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forminfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKey(Forminfo record);
}