package com.smartfactory.model.dao;

import com.smartfactory.model.entity.Goodinfo;
import com.smartfactory.model.entity.GoodinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    long countByExample(GoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByExample(GoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insert(Goodinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insertSelective(Goodinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    List<Goodinfo> selectByExample(GoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    Goodinfo selectByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Goodinfo record, @Param("example") GoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExample(@Param("record") Goodinfo record, @Param("example") GoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKeySelective(Goodinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKey(Goodinfo record);
}