package com.smartfactory.model.dao;

import com.smartfactory.model.entity.Planinfo;
import com.smartfactory.model.entity.PlaninfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlaninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    long countByExample(PlaninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByExample(PlaninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insert(Planinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int insertSelective(Planinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    List<Planinfo> selectByExample(PlaninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    Planinfo selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Planinfo record, @Param("example") PlaninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByExample(@Param("record") Planinfo record, @Param("example") PlaninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKeySelective(Planinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    int updateByPrimaryKey(Planinfo record);
}