package com.smartfactory.model.entity;

public class Bforminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.bfid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer bfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.fid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.pnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer pnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.qnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer qnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.stime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.etime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String etime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.isend
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer isend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bforminfo.note
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.bfid
     *
     * @return the value of bforminfo.bfid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getBfid() {
        return bfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.bfid
     *
     * @param bfid the value for bforminfo.bfid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setBfid(Integer bfid) {
        this.bfid = bfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.fid
     *
     * @return the value of bforminfo.fid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.fid
     *
     * @param fid the value for bforminfo.fid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.gname
     *
     * @return the value of bforminfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.gname
     *
     * @param gname the value for bforminfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.pnum
     *
     * @return the value of bforminfo.pnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getPnum() {
        return pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.pnum
     *
     * @param pnum the value for bforminfo.pnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setPnum(Integer pnum) {
        this.pnum = pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.qnum
     *
     * @return the value of bforminfo.qnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getQnum() {
        return qnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.qnum
     *
     * @param qnum the value for bforminfo.qnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setQnum(Integer qnum) {
        this.qnum = qnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.stime
     *
     * @return the value of bforminfo.stime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.stime
     *
     * @param stime the value for bforminfo.stime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setStime(String stime) {
        this.stime = stime == null ? null : stime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.etime
     *
     * @return the value of bforminfo.etime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.etime
     *
     * @param etime the value for bforminfo.etime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setEtime(String etime) {
        this.etime = etime == null ? null : etime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.isend
     *
     * @return the value of bforminfo.isend
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.isend
     *
     * @param isend the value for bforminfo.isend
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bforminfo.note
     *
     * @return the value of bforminfo.note
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bforminfo.note
     *
     * @param note the value for bforminfo.note
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

	@Override
	public String toString() {
		return "Bforminfo [bfid=" + bfid + ", fid=" + fid + ", gname=" + gname + ", pnum=" + pnum + ", qnum=" + qnum
				+ ", stime=" + stime + ", etime=" + etime + ", isend=" + isend + ", note=" + note + "]";
	}

	public Bforminfo(Integer bfid, Integer fid, String gname, Integer pnum, Integer qnum, String stime, String etime,
			Integer isend, String note) {
		super();
		this.bfid = bfid;
		this.fid = fid;
		this.gname = gname;
		this.pnum = pnum;
		this.qnum = qnum;
		this.stime = stime;
		this.etime = etime;
		this.isend = isend;
		this.note = note;
	}

	public Bforminfo() {
		super();
	}
    
}