package com.smartfactory.model.entity;

public class Forminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.formid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer formid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.fstarttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String fstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.fendtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String fendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.fcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String fcond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.comnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer comnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forminfo.eqpid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer eqpid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.formid
     *
     * @return the value of forminfo.formid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.formid
     *
     * @param formid the value for forminfo.formid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setFormid(Integer formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.orderid
     *
     * @return the value of forminfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.orderid
     *
     * @param orderid the value for forminfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.pid
     *
     * @return the value of forminfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.pid
     *
     * @param pid the value for forminfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.fstarttime
     *
     * @return the value of forminfo.fstarttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getFstarttime() {
        return fstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.fstarttime
     *
     * @param fstarttime the value for forminfo.fstarttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setFstarttime(String fstarttime) {
        this.fstarttime = fstarttime == null ? null : fstarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.fendtime
     *
     * @return the value of forminfo.fendtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getFendtime() {
        return fendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.fendtime
     *
     * @param fendtime the value for forminfo.fendtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setFendtime(String fendtime) {
        this.fendtime = fendtime == null ? null : fendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.fcond
     *
     * @return the value of forminfo.fcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getFcond() {
        return fcond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.fcond
     *
     * @param fcond the value for forminfo.fcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setFcond(String fcond) {
        this.fcond = fcond == null ? null : fcond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.comnum
     *
     * @return the value of forminfo.comnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getComnum() {
        return comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.comnum
     *
     * @param comnum the value for forminfo.comnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setComnum(Integer comnum) {
        this.comnum = comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.gname
     *
     * @return the value of forminfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.gname
     *
     * @param gname the value for forminfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forminfo.eqpid
     *
     * @return the value of forminfo.eqpid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getEqpid() {
        return eqpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forminfo.eqpid
     *
     * @param eqpid the value for forminfo.eqpid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setEqpid(Integer eqpid) {
        this.eqpid = eqpid;
    }

	@Override
	public String toString() {
		return "Forminfo [formid=" + formid + ", orderid=" + orderid + ", pid=" + pid + ", fstarttime=" + fstarttime
				+ ", fendtime=" + fendtime + ", fcond=" + fcond + ", comnum=" + comnum + ", gname=" + gname + ", eqpid="
				+ eqpid + "]";
	}

	public Forminfo(Integer formid, Integer orderid, Integer pid, String fstarttime, String fendtime, String fcond,
			Integer comnum, String gname, Integer eqpid) {
		super();
		this.formid = formid;
		this.orderid = orderid;
		this.pid = pid;
		this.fstarttime = fstarttime;
		this.fendtime = fendtime;
		this.fcond = fcond;
		this.comnum = comnum;
		this.gname = gname;
		this.eqpid = eqpid;
	}

	public Forminfo() {
		super();
	}
    
}