package com.smartfactory.model.entity;

import java.util.ArrayList;
import java.util.List;

public class GoodinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public GoodinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(Integer value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(Integer value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(Integer value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(Integer value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(Integer value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<Integer> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<Integer> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(Integer value1, Integer value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(Integer value1, Integer value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGnameIsNull() {
            addCriterion("gname is null");
            return (Criteria) this;
        }

        public Criteria andGnameIsNotNull() {
            addCriterion("gname is not null");
            return (Criteria) this;
        }

        public Criteria andGnameEqualTo(String value) {
            addCriterion("gname =", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotEqualTo(String value) {
            addCriterion("gname <>", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThan(String value) {
            addCriterion("gname >", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThanOrEqualTo(String value) {
            addCriterion("gname >=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThan(String value) {
            addCriterion("gname <", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThanOrEqualTo(String value) {
            addCriterion("gname <=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLike(String value) {
            addCriterion("gname like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotLike(String value) {
            addCriterion("gname not like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameIn(List<String> values) {
            addCriterion("gname in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotIn(List<String> values) {
            addCriterion("gname not in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameBetween(String value1, String value2) {
            addCriterion("gname between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotBetween(String value1, String value2) {
            addCriterion("gname not between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGpicIsNull() {
            addCriterion("gpic is null");
            return (Criteria) this;
        }

        public Criteria andGpicIsNotNull() {
            addCriterion("gpic is not null");
            return (Criteria) this;
        }

        public Criteria andGpicEqualTo(String value) {
            addCriterion("gpic =", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicNotEqualTo(String value) {
            addCriterion("gpic <>", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicGreaterThan(String value) {
            addCriterion("gpic >", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicGreaterThanOrEqualTo(String value) {
            addCriterion("gpic >=", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicLessThan(String value) {
            addCriterion("gpic <", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicLessThanOrEqualTo(String value) {
            addCriterion("gpic <=", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicLike(String value) {
            addCriterion("gpic like", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicNotLike(String value) {
            addCriterion("gpic not like", value, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicIn(List<String> values) {
            addCriterion("gpic in", values, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicNotIn(List<String> values) {
            addCriterion("gpic not in", values, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicBetween(String value1, String value2) {
            addCriterion("gpic between", value1, value2, "gpic");
            return (Criteria) this;
        }

        public Criteria andGpicNotBetween(String value1, String value2) {
            addCriterion("gpic not between", value1, value2, "gpic");
            return (Criteria) this;
        }

        public Criteria andGcapIsNull() {
            addCriterion("gcap is null");
            return (Criteria) this;
        }

        public Criteria andGcapIsNotNull() {
            addCriterion("gcap is not null");
            return (Criteria) this;
        }

        public Criteria andGcapEqualTo(Integer value) {
            addCriterion("gcap =", value, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapNotEqualTo(Integer value) {
            addCriterion("gcap <>", value, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapGreaterThan(Integer value) {
            addCriterion("gcap >", value, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapGreaterThanOrEqualTo(Integer value) {
            addCriterion("gcap >=", value, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapLessThan(Integer value) {
            addCriterion("gcap <", value, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapLessThanOrEqualTo(Integer value) {
            addCriterion("gcap <=", value, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapIn(List<Integer> values) {
            addCriterion("gcap in", values, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapNotIn(List<Integer> values) {
            addCriterion("gcap not in", values, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapBetween(Integer value1, Integer value2) {
            addCriterion("gcap between", value1, value2, "gcap");
            return (Criteria) this;
        }

        public Criteria andGcapNotBetween(Integer value1, Integer value2) {
            addCriterion("gcap not between", value1, value2, "gcap");
            return (Criteria) this;
        }

        public Criteria andEqpnameIsNull() {
            addCriterion("eqpname is null");
            return (Criteria) this;
        }

        public Criteria andEqpnameIsNotNull() {
            addCriterion("eqpname is not null");
            return (Criteria) this;
        }

        public Criteria andEqpnameEqualTo(String value) {
            addCriterion("eqpname =", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameNotEqualTo(String value) {
            addCriterion("eqpname <>", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameGreaterThan(String value) {
            addCriterion("eqpname >", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameGreaterThanOrEqualTo(String value) {
            addCriterion("eqpname >=", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameLessThan(String value) {
            addCriterion("eqpname <", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameLessThanOrEqualTo(String value) {
            addCriterion("eqpname <=", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameLike(String value) {
            addCriterion("eqpname like", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameNotLike(String value) {
            addCriterion("eqpname not like", value, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameIn(List<String> values) {
            addCriterion("eqpname in", values, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameNotIn(List<String> values) {
            addCriterion("eqpname not in", values, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameBetween(String value1, String value2) {
            addCriterion("eqpname between", value1, value2, "eqpname");
            return (Criteria) this;
        }

        public Criteria andEqpnameNotBetween(String value1, String value2) {
            addCriterion("eqpname not between", value1, value2, "eqpname");
            return (Criteria) this;
        }

        public Criteria andOfcondIsNull() {
            addCriterion("ofcond is null");
            return (Criteria) this;
        }

        public Criteria andOfcondIsNotNull() {
            addCriterion("ofcond is not null");
            return (Criteria) this;
        }

        public Criteria andOfcondEqualTo(String value) {
            addCriterion("ofcond =", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotEqualTo(String value) {
            addCriterion("ofcond <>", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondGreaterThan(String value) {
            addCriterion("ofcond >", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondGreaterThanOrEqualTo(String value) {
            addCriterion("ofcond >=", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondLessThan(String value) {
            addCriterion("ofcond <", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondLessThanOrEqualTo(String value) {
            addCriterion("ofcond <=", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondLike(String value) {
            addCriterion("ofcond like", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotLike(String value) {
            addCriterion("ofcond not like", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondIn(List<String> values) {
            addCriterion("ofcond in", values, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotIn(List<String> values) {
            addCriterion("ofcond not in", values, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondBetween(String value1, String value2) {
            addCriterion("ofcond between", value1, value2, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotBetween(String value1, String value2) {
            addCriterion("ofcond not between", value1, value2, "ofcond");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goodinfo
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 26 09:40:03 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goodinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}