package com.smartfactory.model.entity;

public class Goodinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodinfo.gid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodinfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodinfo.gpic
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String gpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodinfo.gcap
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer gcap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodinfo.eqpname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String eqpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodinfo.ofcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String ofcond;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodinfo.gid
     *
     * @return the value of goodinfo.gid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodinfo.gid
     *
     * @param gid the value for goodinfo.gid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodinfo.gname
     *
     * @return the value of goodinfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodinfo.gname
     *
     * @param gname the value for goodinfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodinfo.gpic
     *
     * @return the value of goodinfo.gpic
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getGpic() {
        return gpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodinfo.gpic
     *
     * @param gpic the value for goodinfo.gpic
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGpic(String gpic) {
        this.gpic = gpic == null ? null : gpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodinfo.gcap
     *
     * @return the value of goodinfo.gcap
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getGcap() {
        return gcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodinfo.gcap
     *
     * @param gcap the value for goodinfo.gcap
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGcap(Integer gcap) {
        this.gcap = gcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodinfo.eqpname
     *
     * @return the value of goodinfo.eqpname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getEqpname() {
        return eqpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodinfo.eqpname
     *
     * @param eqpname the value for goodinfo.eqpname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setEqpname(String eqpname) {
        this.eqpname = eqpname == null ? null : eqpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodinfo.ofcond
     *
     * @return the value of goodinfo.ofcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOfcond() {
        return ofcond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodinfo.ofcond
     *
     * @param ofcond the value for goodinfo.ofcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOfcond(String ofcond) {
        this.ofcond = ofcond == null ? null : ofcond.trim();
    }

	@Override
	public String toString() {
		return "Goodinfo [gid=" + gid + ", gname=" + gname + ", gpic=" + gpic + ", gcap=" + gcap + ", eqpname="
				+ eqpname + ", ofcond=" + ofcond + "]";
	}

	public Goodinfo(Integer gid, String gname, String gpic, Integer gcap, String eqpname, String ofcond) {
		super();
		this.gid = gid;
		this.gname = gname;
		this.gpic = gpic;
		this.gcap = gcap;
		this.eqpname = eqpname;
		this.ofcond = ofcond;
	}

	public Goodinfo() {
		super();
	}
    
}