package com.smartfactory.model.entity;

public class Orderinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ofsou
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String ofsou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.gnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer gnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ofcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String ofcond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.userid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.note
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.comnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer comnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ostarttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String ostarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.oendtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String oendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.gid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderid
     *
     * @return the value of orderinfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderid
     *
     * @param orderid the value for orderinfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ofsou
     *
     * @return the value of orderinfo.ofsou
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOfsou() {
        return ofsou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ofsou
     *
     * @param ofsou the value for orderinfo.ofsou
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOfsou(String ofsou) {
        this.ofsou = ofsou == null ? null : ofsou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.gname
     *
     * @return the value of orderinfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.gname
     *
     * @param gname the value for orderinfo.gname
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.gnum
     *
     * @return the value of orderinfo.gnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getGnum() {
        return gnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.gnum
     *
     * @param gnum the value for orderinfo.gnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGnum(Integer gnum) {
        this.gnum = gnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ofcond
     *
     * @return the value of orderinfo.ofcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOfcond() {
        return ofcond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ofcond
     *
     * @param ofcond the value for orderinfo.ofcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOfcond(String ofcond) {
        this.ofcond = ofcond == null ? null : ofcond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.userid
     *
     * @return the value of orderinfo.userid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.userid
     *
     * @param userid the value for orderinfo.userid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.note
     *
     * @return the value of orderinfo.note
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.note
     *
     * @param note the value for orderinfo.note
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.comnum
     *
     * @return the value of orderinfo.comnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getComnum() {
        return comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.comnum
     *
     * @param comnum the value for orderinfo.comnum
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setComnum(Integer comnum) {
        this.comnum = comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ostarttime
     *
     * @return the value of orderinfo.ostarttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOstarttime() {
        return ostarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ostarttime
     *
     * @param ostarttime the value for orderinfo.ostarttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOstarttime(String ostarttime) {
        this.ostarttime = ostarttime == null ? null : ostarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.oendtime
     *
     * @return the value of orderinfo.oendtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOendtime() {
        return oendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.oendtime
     *
     * @param oendtime the value for orderinfo.oendtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOendtime(String oendtime) {
        this.oendtime = oendtime == null ? null : oendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.pid
     *
     * @return the value of orderinfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.pid
     *
     * @param pid the value for orderinfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.gid
     *
     * @return the value of orderinfo.gid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.gid
     *
     * @param gid the value for orderinfo.gid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

	@Override
	public String toString() {
		return "Orderinfo [orderid=" + orderid + ", ofsou=" + ofsou + ", gname=" + gname + ", gnum=" + gnum
				+ ", ofcond=" + ofcond + ", userid=" + userid + ", note=" + note + ", comnum=" + comnum
				+ ", ostarttime=" + ostarttime + ", oendtime=" + oendtime + ", pid=" + pid + ", gid=" + gid + "]";
	}

	public Orderinfo(Integer orderid, String ofsou, String gname, Integer gnum, String ofcond, Integer userid,
			String note, Integer comnum, String ostarttime, String oendtime, Integer pid, Integer gid) {
		super();
		this.orderid = orderid;
		this.ofsou = ofsou;
		this.gname = gname;
		this.gnum = gnum;
		this.ofcond = ofcond;
		this.userid = userid;
		this.note = note;
		this.comnum = comnum;
		this.ostarttime = ostarttime;
		this.oendtime = oendtime;
		this.pid = pid;
		this.gid = gid;
	}

	public Orderinfo() {
		super();
	}
    
}