package com.smartfactory.model.entity;

import java.util.ArrayList;
import java.util.List;

public class OrderinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public OrderinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOfsouIsNull() {
            addCriterion("ofsou is null");
            return (Criteria) this;
        }

        public Criteria andOfsouIsNotNull() {
            addCriterion("ofsou is not null");
            return (Criteria) this;
        }

        public Criteria andOfsouEqualTo(String value) {
            addCriterion("ofsou =", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouNotEqualTo(String value) {
            addCriterion("ofsou <>", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouGreaterThan(String value) {
            addCriterion("ofsou >", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouGreaterThanOrEqualTo(String value) {
            addCriterion("ofsou >=", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouLessThan(String value) {
            addCriterion("ofsou <", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouLessThanOrEqualTo(String value) {
            addCriterion("ofsou <=", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouLike(String value) {
            addCriterion("ofsou like", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouNotLike(String value) {
            addCriterion("ofsou not like", value, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouIn(List<String> values) {
            addCriterion("ofsou in", values, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouNotIn(List<String> values) {
            addCriterion("ofsou not in", values, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouBetween(String value1, String value2) {
            addCriterion("ofsou between", value1, value2, "ofsou");
            return (Criteria) this;
        }

        public Criteria andOfsouNotBetween(String value1, String value2) {
            addCriterion("ofsou not between", value1, value2, "ofsou");
            return (Criteria) this;
        }

        public Criteria andGnameIsNull() {
            addCriterion("gname is null");
            return (Criteria) this;
        }

        public Criteria andGnameIsNotNull() {
            addCriterion("gname is not null");
            return (Criteria) this;
        }

        public Criteria andGnameEqualTo(String value) {
            addCriterion("gname =", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotEqualTo(String value) {
            addCriterion("gname <>", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThan(String value) {
            addCriterion("gname >", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThanOrEqualTo(String value) {
            addCriterion("gname >=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThan(String value) {
            addCriterion("gname <", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThanOrEqualTo(String value) {
            addCriterion("gname <=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLike(String value) {
            addCriterion("gname like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotLike(String value) {
            addCriterion("gname not like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameIn(List<String> values) {
            addCriterion("gname in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotIn(List<String> values) {
            addCriterion("gname not in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameBetween(String value1, String value2) {
            addCriterion("gname between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotBetween(String value1, String value2) {
            addCriterion("gname not between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGnumIsNull() {
            addCriterion("gnum is null");
            return (Criteria) this;
        }

        public Criteria andGnumIsNotNull() {
            addCriterion("gnum is not null");
            return (Criteria) this;
        }

        public Criteria andGnumEqualTo(Integer value) {
            addCriterion("gnum =", value, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumNotEqualTo(Integer value) {
            addCriterion("gnum <>", value, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumGreaterThan(Integer value) {
            addCriterion("gnum >", value, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("gnum >=", value, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumLessThan(Integer value) {
            addCriterion("gnum <", value, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumLessThanOrEqualTo(Integer value) {
            addCriterion("gnum <=", value, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumIn(List<Integer> values) {
            addCriterion("gnum in", values, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumNotIn(List<Integer> values) {
            addCriterion("gnum not in", values, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumBetween(Integer value1, Integer value2) {
            addCriterion("gnum between", value1, value2, "gnum");
            return (Criteria) this;
        }

        public Criteria andGnumNotBetween(Integer value1, Integer value2) {
            addCriterion("gnum not between", value1, value2, "gnum");
            return (Criteria) this;
        }

        public Criteria andOfcondIsNull() {
            addCriterion("ofcond is null");
            return (Criteria) this;
        }

        public Criteria andOfcondIsNotNull() {
            addCriterion("ofcond is not null");
            return (Criteria) this;
        }

        public Criteria andOfcondEqualTo(String value) {
            addCriterion("ofcond =", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotEqualTo(String value) {
            addCriterion("ofcond <>", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondGreaterThan(String value) {
            addCriterion("ofcond >", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondGreaterThanOrEqualTo(String value) {
            addCriterion("ofcond >=", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondLessThan(String value) {
            addCriterion("ofcond <", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondLessThanOrEqualTo(String value) {
            addCriterion("ofcond <=", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondLike(String value) {
            addCriterion("ofcond like", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotLike(String value) {
            addCriterion("ofcond not like", value, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondIn(List<String> values) {
            addCriterion("ofcond in", values, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotIn(List<String> values) {
            addCriterion("ofcond not in", values, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondBetween(String value1, String value2) {
            addCriterion("ofcond between", value1, value2, "ofcond");
            return (Criteria) this;
        }

        public Criteria andOfcondNotBetween(String value1, String value2) {
            addCriterion("ofcond not between", value1, value2, "ofcond");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andComnumIsNull() {
            addCriterion("comnum is null");
            return (Criteria) this;
        }

        public Criteria andComnumIsNotNull() {
            addCriterion("comnum is not null");
            return (Criteria) this;
        }

        public Criteria andComnumEqualTo(Integer value) {
            addCriterion("comnum =", value, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumNotEqualTo(Integer value) {
            addCriterion("comnum <>", value, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumGreaterThan(Integer value) {
            addCriterion("comnum >", value, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("comnum >=", value, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumLessThan(Integer value) {
            addCriterion("comnum <", value, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumLessThanOrEqualTo(Integer value) {
            addCriterion("comnum <=", value, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumIn(List<Integer> values) {
            addCriterion("comnum in", values, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumNotIn(List<Integer> values) {
            addCriterion("comnum not in", values, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumBetween(Integer value1, Integer value2) {
            addCriterion("comnum between", value1, value2, "comnum");
            return (Criteria) this;
        }

        public Criteria andComnumNotBetween(Integer value1, Integer value2) {
            addCriterion("comnum not between", value1, value2, "comnum");
            return (Criteria) this;
        }

        public Criteria andOstarttimeIsNull() {
            addCriterion("ostarttime is null");
            return (Criteria) this;
        }

        public Criteria andOstarttimeIsNotNull() {
            addCriterion("ostarttime is not null");
            return (Criteria) this;
        }

        public Criteria andOstarttimeEqualTo(String value) {
            addCriterion("ostarttime =", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeNotEqualTo(String value) {
            addCriterion("ostarttime <>", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeGreaterThan(String value) {
            addCriterion("ostarttime >", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeGreaterThanOrEqualTo(String value) {
            addCriterion("ostarttime >=", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeLessThan(String value) {
            addCriterion("ostarttime <", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeLessThanOrEqualTo(String value) {
            addCriterion("ostarttime <=", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeLike(String value) {
            addCriterion("ostarttime like", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeNotLike(String value) {
            addCriterion("ostarttime not like", value, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeIn(List<String> values) {
            addCriterion("ostarttime in", values, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeNotIn(List<String> values) {
            addCriterion("ostarttime not in", values, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeBetween(String value1, String value2) {
            addCriterion("ostarttime between", value1, value2, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOstarttimeNotBetween(String value1, String value2) {
            addCriterion("ostarttime not between", value1, value2, "ostarttime");
            return (Criteria) this;
        }

        public Criteria andOendtimeIsNull() {
            addCriterion("oendtime is null");
            return (Criteria) this;
        }

        public Criteria andOendtimeIsNotNull() {
            addCriterion("oendtime is not null");
            return (Criteria) this;
        }

        public Criteria andOendtimeEqualTo(String value) {
            addCriterion("oendtime =", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeNotEqualTo(String value) {
            addCriterion("oendtime <>", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeGreaterThan(String value) {
            addCriterion("oendtime >", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeGreaterThanOrEqualTo(String value) {
            addCriterion("oendtime >=", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeLessThan(String value) {
            addCriterion("oendtime <", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeLessThanOrEqualTo(String value) {
            addCriterion("oendtime <=", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeLike(String value) {
            addCriterion("oendtime like", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeNotLike(String value) {
            addCriterion("oendtime not like", value, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeIn(List<String> values) {
            addCriterion("oendtime in", values, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeNotIn(List<String> values) {
            addCriterion("oendtime not in", values, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeBetween(String value1, String value2) {
            addCriterion("oendtime between", value1, value2, "oendtime");
            return (Criteria) this;
        }

        public Criteria andOendtimeNotBetween(String value1, String value2) {
            addCriterion("oendtime not between", value1, value2, "oendtime");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(Integer value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(Integer value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(Integer value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(Integer value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(Integer value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<Integer> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<Integer> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(Integer value1, Integer value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(Integer value1, Integer value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 26 09:40:03 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}