package com.smartfactory.model.entity;

public class Planinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.formid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer formid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.starttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.endtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.pcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String pcond;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.pid
     *
     * @return the value of planinfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.pid
     *
     * @param pid the value for planinfo.pid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.orderid
     *
     * @return the value of planinfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.orderid
     *
     * @param orderid the value for planinfo.orderid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.formid
     *
     * @return the value of planinfo.formid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.formid
     *
     * @param formid the value for planinfo.formid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setFormid(Integer formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.starttime
     *
     * @return the value of planinfo.starttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.starttime
     *
     * @param starttime the value for planinfo.starttime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.endtime
     *
     * @return the value of planinfo.endtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.endtime
     *
     * @param endtime the value for planinfo.endtime
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.pcond
     *
     * @return the value of planinfo.pcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getPcond() {
        return pcond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.pcond
     *
     * @param pcond the value for planinfo.pcond
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setPcond(String pcond) {
        this.pcond = pcond == null ? null : pcond.trim();
    }

	@Override
	public String toString() {
		return "Planinfo [pid=" + pid + ", orderid=" + orderid + ", formid=" + formid + ", starttime=" + starttime
				+ ", endtime=" + endtime + ", pcond=" + pcond + "]";
	}

	public Planinfo() {
		super();
	}

	public Planinfo(Integer pid, Integer orderid, Integer formid, String starttime, String endtime, String pcond) {
		super();
		this.pid = pid;
		this.orderid = orderid;
		this.formid = formid;
		this.starttime = starttime;
		this.endtime = endtime;
		this.pcond = pcond;
	}



    
}