package com.smartfactory.model.entity;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpwd
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.useremail
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private String useremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpow
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    private Integer userpow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpwd
     *
     * @return the value of userinfo.userpwd
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpwd
     *
     * @param userpwd the value for userinfo.userpwd
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.useremail
     *
     * @return the value of userinfo.useremail
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.useremail
     *
     * @param useremail the value for userinfo.useremail
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpow
     *
     * @return the value of userinfo.userpow
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public Integer getUserpow() {
        return userpow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpow
     *
     * @param userpow the value for userinfo.userpow
     *
     * @mbg.generated Sun Jul 26 09:40:03 CST 2020
     */
    public void setUserpow(Integer userpow) {
        this.userpow = userpow;
    }

	@Override
	public String toString() {
		return "Userinfo [userid=" + userid + ", username=" + username + ", userpwd=" + userpwd + ", useremail="
				+ useremail + ", userpow=" + userpow + "]";
	}

	public Userinfo(Integer userid, String username, String userpwd, String useremail, Integer userpow) {
		super();
		this.userid = userid;
		this.username = username;
		this.userpwd = userpwd;
		this.useremail = useremail;
		this.userpow = userpow;
	}

	public Userinfo() {
		super();
	}
    
}